repository: amaprouen/amaprouen.github.io
# Site settings
title: AMAP Rouen
url: http://amaprouen.org
#theme: minima
theme: minima
markdown: kramdown
sass:
  style: compressed
gems:
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
