repository: amaprouen/amaprouen.github.io
# Configuration
title: AMAP Rouen
description: AMAP Rouen, pour le maintien d'une agriculture paysanne
url: http://amaprouen.org

#theme: minima
theme: minima
markdown: kramdown
sass:
  style: compressed
plugins:
  - jekyll-sitemap
  - jekyll-feed

# Front matter par défaut
defaults:
  - scope:
      path: ""
      types: pages
    values:
      layout: default

# Utiliser un repéertoire "_pages"
collections:
  pages:
    output: true
    permalink: /:path
